name: Dependency Management

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Ensure go.mod and go.sum are tidy
      run: go mod tidy -v

