name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Read README.md
      id: read_readme
      run: echo "README_CONTENT=$(cat README.md)" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: "README.md"
        body: ${{ env.README_CONTENT }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

